config/routes.rb
FieldableFormExampleApp::Application.routes.draw do
  resources :products
  resources :product_types
  root :to => 'product_types#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  include FieldableForm::EntryValidations

  attr_accessible :name, :product_type_id, :properties
  belongs_to :product_type

  serialize :properties, Hash

  validate_fieldable_form_entry :form_to_validate, :properties

  private
    def form_to_validate
      product_type.product_form
    end
end

app/models/product_form.rb
class ProductForm < ActiveRecord::Base
  attr_accessible :product_type_id, :fields_attributes

  belongs_to :product_type

  has_many :fields, :class_name => FieldableForm::Field, :as => :fieldable, :dependent => :destroy
  accepts_nested_attributes_for :fields, :allow_destroy => true
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  attr_accessible :name, :product_form_attributes
  has_one :product_form

  accepts_nested_attributes_for :product_form

  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_types }
    end
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
    @product_type = ProductType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_type }
    end
  end

  # GET /product_types/new
  # GET /product_types/new.json
  def new
    @product_type = ProductType.new
    @product_type.build_product_form

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product_type }
    end
  end

  # GET /product_types/1/edit
  def edit
    @product_type = ProductType.find(params[:id])
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(params[:product_type])

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Product type was successfully created.' }
        format.json { render json: @product_type, status: :created, location: @product_type }
      else
        format.html { render action: "new" }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /product_types/1
  # PUT /product_types/1.json
  def update
    @product_type = ProductType.find(params[:id])

    respond_to do |format|
      if @product_type.update_attributes(params[:product_type])
        format.html { redirect_to @product_type, notice: 'Product type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type = ProductType.find(params[:id])
    @product_type.destroy

    respond_to do |format|
      format.html { redirect_to product_types_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new(:product_type_id => params[:product_type_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/product_form_helper.rb
module ProductFormHelper

  # @param [ActionView::Helpers::FormBuilder] f The rails form builder object.
  # @param [String, Symbol] field_type The field type, currently can only be :text_field, :drop_down or :check_box.
  # @param [String] partial The partial to render when a field is added.
  # @param [Hash] html_options The html options for the <a> tag. This options will be passed to the rails
  #   default link_to helper.
  # @return a link with approriate data atrribute so that the right js will be hooked
  #   and when clicked will add a new field.
  def product_form_add_field(f, name, field_type, target, partial, html_options = {})
    partial ||= association.to_s.singularize + "_fields"
    klass = "FieldableForm::#{field_type.to_s.camelize}".constantize
    new_object = klass.new
    
    id = new_object.object_id
    fields = f.fields_for(:fields, new_object, child_index: id) do |builder|
      render(partial, f: builder)
    end

    default = { data: { product_form: 'add_field', target: target, id: id, fields: fields.gsub("\n", "") } }
    html_options = default.deep_merge(html_options)
    link_to(name, '#', html_options)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dummy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product_forms/builder/_check_box.html.erb
<fieldset>
  <%= f.hidden_field :type, :value => 'FieldableForm::CheckBox' %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.hidden_field :_destroy %>
  <%= link_to '[remove]', '#', data: { product_form: 'remove_field' } %>
</fieldset>

app/views/product_forms/builder/_drop_down.html.erb
<fieldset>
  <%= f.hidden_field :type, :value => 'FieldableForm::DropDown' %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :required %>
  <%= f.check_box :required %>

  <%= f.label :include_blank %>
  <%= f.check_box :include_blank %>

  <%= f.label :items %>
  <%= f.text_area :items %>

  <%= f.hidden_field :_destroy %>
  <%= link_to '[remove]', '#', data: { product_form: 'remove_field' } %>
</fieldset>

app/views/product_forms/builder/_fields.html.erb
<div id="fields_section">
  <%= f.fields_for :fields do |ff| %>
    <%= render "product_forms/builder/#{ff.object.type.demodulize.underscore}", f: ff %>
  <% end %>
</div>

<%= product_form_add_field f, "Add Text Field", :text_field, '#fields_section', 'product_forms/builder/text_field' %>
<%= product_form_add_field f, "Add Drop Down", :drop_down, '#fields_section', 'product_forms/builder/drop_down' %>
<%= product_form_add_field f, "Add Check Box", :check_box, '#fields_section', 'product_forms/builder/check_box' %>

app/views/product_forms/builder/_text_field.html.erb
<fieldset>
  <%= f.hidden_field :type, :value => 'FieldableForm::TextField' %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :required %>
  <%= f.check_box :required %>

  <%= f.label :number_only %>
  <%= f.check_box :number_only %>

  <%= f.label :min_length %>
  <%= f.text_field :min_length %>

  <%= f.label :max_length %>
  <%= f.text_field :max_length %>

  <%= f.hidden_field :_destroy %>
  <%= link_to '[remove]', '#', data: { product_form: 'remove_field' } %>
</fieldset>

app/views/product_forms/entry/_field.html.erb
<div class="field">
  <%= f.label field.name %>
  <%= f.send(field.render_method, *field.render_options) %>
</div>

app/views/product_types/_form.html.erb
<%= form_for(@product_type) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
      <% @product_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :product_form do |form_builder| %>
    <%= render 'product_forms/builder/fields', f: form_builder %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h1>Editing product_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

app/views/product_types/index.html.erb
<h1>Listing product_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @product_types.each do |product_type| %>
  <tr>
    <td><%= product_type.name %></td>
    <td><%= link_to 'Show', product_type %></td>
    <td><%= link_to 'Edit', edit_product_type_path(product_type) %></td>
    <td><%= link_to 'Destroy', product_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product type', new_product_type_path %>
<%= link_to 'View all products', products_path %>

app/views/product_types/new.html.erb
<h1>New product_type</h1>

<%= render 'form' %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product_type.name %>
</p>


<%= link_to 'Edit', edit_product_type_path(@product_type) %> |
<%= link_to 'Back', product_types_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :product_type_id %>

  <%= f.fields_for :properties, OpenStruct.new(@product.properties) do |ff| %>
    <% @product.product_type.product_form.fields.each do |field| %>
      <%= render  "product_forms/entry/field", f: ff, field: field %>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Product type</th>
    <th>Properties</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.product_type_id %></td>
    <td><%= product.properties %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= form_tag new_product_path, method: :get do %>
  <%= select_tag :product_type_id, options_from_collection_for_select(ProductType.all, :id, :name) %>
  <%= submit_tag "New Product", name: nil %>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product type:</b>
  <%= @product.product_type_id %>
</p>

<p>
  <b>Properties:</b>
  <%= @product.properties %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>